#!/bin/bash

mkdir -p FEMApp/Release

./compilerelease FEMApp/FEMAppLib
result=$?
if [[ $result -ne 0 ]]; then
	exit $result
fi
./compilerelease FEMApp/FEMGraphLib
result=$?
if [[ $result -ne 0 ]]; then
	exit $result
fi
./compilerelease FEMApp/FEMGraphLib
result=$?
if [[ $result -ne 0 ]]; then
	exit $result
fi
./compilerelease FEMApp/FEMLib
result=$?
if [[ $result -ne 0 ]]; then
	exit $result
fi
./compilerelease FEMApp/GraphLib
result=$?
if [[ $result -ne 0 ]]; then
	exit $result
fi
./compilerelease FEMApp/XMLLib
result=$?
if [[ $result -ne 0 ]]; then
	exit $result
fi
./compilerelease FEMApp/MolecularLib
result=$?
if [[ $result -ne 0 ]]; then
	exit $result
fi
./compilerelease FEMApp/LangLib
result=$?
if [[ $result -ne 0 ]]; then
	exit $result
fi
./compilerelease FEMApp/MathLib
result=$?
if [[ $result -ne 0 ]]; then
	exit $result
fi
./compilerelease FEMApp/CoupledFields
result=$?
if [[ $result -ne 0 ]]; then
	exit $result
fi

