#ifndef FEA_STAGES_H
#define FEA_STAGES_H

enum FEA_Stages
{
    ST_BEGIN_OF_ANALYSIS,
    ST_BEGIN_OF_STEP,
    ST_BEGIN_OF_ITERATIONS,
    ST_NEXT_ITERATION,
    ST_END_OF_ITERATIONS,
    ST_NEXT_STEP,
    ST_END_OF_STEP,
    ST_END_OF_ANALYSIS
};

#endif // FEA_STAGES_H
