
/* This is a quick hack to isloate system dependent informaion. AT the
   end of the day this will be generated by cmake, but we can not do
   that until qmake goes away. */
static const QString PATH = "/path/to/docs";
