// Class automatically generated by Dev-C++ New Class wizard

#ifndef CXML_ELEMENT_H
#define CXML_ELEMENT_H

/**
 * No description
 */

#include "xml_exceptions.h"
#include "xml_outputdevice.h"

#include <string>
#include <list>
#include <vector>
using namespace std;

class CXML_Element
{
public:
		
		// class constructor
		CXML_Element( const string &n, int tp ):name( n ),type( tp ) {  }
		const string& GetName() const { return name; }
		const int GetType() const { return type; }
		virtual ~CXML_Element( ) { }
protected:
	CXML_Element():name( "" ),type( 0 ) {  }
	int type;
    string  name;
};

typedef list< CXML_Element* >  ListOfElements;


class CElemPredicator
{
	const string fname;
	const unsigned ftype;
public:
	CElemPredicator( unsigned ft, const string &fn):ftype(ft),fname(fn) { }
	bool operator()(  const CXML_Element *el ) const { return el->GetName( ) == fname && el->GetType( ) == ftype; }
};



#endif
