// Class automatically generated by Dev-C++ New Class wizard

#ifndef XML_CDATA_H
#define XML_CDATA_H

#include "xml_element.h" // inheriting class's header file
#include "xml_constant.h"
#include "iter_if.h"

/**
 * The class represents CDATA XML element
 */	
class CXML_CDATA : public CXML_Element
{
	public:
		// class constructor
		CXML_CDATA( const string &cd ):CXML_Element("",XML_CDATA),cdata(cd)  { }
		const string& GetData() const { return cdata;  }
		// class destructor
		virtual ~CXML_CDATA( ) { }
protected:
	string cdata;
  	CXML_CDATA()  {  }
};

typedef  iter_if< CXML_CDATA, vector< CXML_Element* >::const_iterator, CElemPredicator > cdata_iterator;

#endif // XML_CDATA_H
