// Class automatically generated by Dev-C++ New Class wizard

#ifndef CXMLOUTPUTDEVICE_H
#define CXMLOUTPUTDEVICE_H

#include <string>
#include <fstream>
using namespace std;


/*
 * No description
 */
 
 
class CXML_OutputDevice
{
    ofstream file;
	public:
		// class constructor
        CXML_OutputDevice( const string &fn );
		// class destructor
		virtual ~CXML_OutputDevice( )   { endl(); file.close(); }
		void write( const string &str ) { file << str; }
		CXML_OutputDevice& operator << ( const string &tx ) { file << tx; return *this; }
		CXML_OutputDevice& operator << (  char c ) { file << c; return *this; }
        CXML_OutputDevice& operator << (  int c ) { file << c; return *this; }
        CXML_OutputDevice& operator << (  unsigned c ) { file << c; return *this; }
        CXML_OutputDevice& operator << (  double c ) { file << c; return *this; }
		void endl( )                    { file << std::endl; }
	    void write_spaces( unsigned n ) { for (unsigned k=0; k<n; k++) file << "  "; }
protected:
   		CXML_OutputDevice() { }
};

#endif
