// Class automatically generated by Dev-C++ New Class wizard

#ifndef CXML_PREPROCESSING_H
#define CXML_PREPROCESSING_H

#include "xml_element.h" // inheriting class's header file
#include "xml_constant.h"
#include "iter_if.h"

/**
 * The class represents xml preprocessing statment
 */
class CXML_Preprocessing : public CXML_Element
{
	public:
		// class constructor
		CXML_Preprocessing(const string n,const string cn):CXML_Element(n,XML_PREPROCESSING),content(cn) { }
		const string& GetContent() const { return content; }
		// class destructor
		virtual ~CXML_Preprocessing() {  }
	protected:
   		CXML_Preprocessing() { }
		string content;
};

typedef  iter_if< CXML_Preprocessing, vector< CXML_Element* >::const_iterator, CElemPredicator > preproc_iterator;

#endif // CXML_PREPROCESSING_H
