// Class automatically generated by Dev-C++ New Class wizard

#ifndef XML_REMARK_H
#define XML_REMARK_H

#include "xml_element.h" // inheriting class's header file
#include "xml_constant.h"
#include "iter_if.h"

/**
 * No description
 */
class CXML_Remark : public CXML_Element
{
	public:
		// class constructor
		CXML_Remark( const string &rm ):CXML_Element( "", XML_REMARK ),remark( rm ) { }
		const string& GetRemark() const { return remark; }
		// class destructor
		virtual ~CXML_Remark() {     }
protected:
    CXML_Remark() { }
	string remark;
};

typedef  iter_if< CXML_Remark, vector< CXML_Element* >::const_iterator, CElemPredicator > remark_iterator;

#endif // XML_REMARK_H
