// Class automatically generated by Dev-C++ New Class wizard

#include "xml_outputdevice.h" // class's header file
#include "xml_exceptions.h" 

CXML_OutputDevice::CXML_OutputDevice( const string &fn )
{ 
    file.open( fn.c_str() );
//    if ( !file.is_open() ) throw CXML_Exception("Error in opening file :" + fn);

}
