// Class automatically generated by Dev-C++ New Class wizard

#ifndef XML_TEXT_H
#define XML_TEXT_H

#include <vector>
using namespace std;

#include "xml_element.h" // inheriting class's header file
#include "xml_constant.h"
#include "iter_if.h"
/**
 * No description
 */
class CXML_Text : public CXML_Element
{
	public:
		// class constructor
		CXML_Text( const string &nm ):CXML_Element( nm, XML_TEXT ) { }
		const string& GetText() { return name; }
		// class destructor
		virtual ~CXML_Text() { }
};

typedef  iter_if< CXML_Text, vector< CXML_Element* >::const_iterator, CElemPredicator > text_iterator;

#endif // XML_TEXT_H
