// Class automatically generated by Dev-C++ New Class wizard

#include "xml_inputdevice.h" // class's header file

// class constructor

void CXML_InputDevice::GetStringUpToString( const string &end, string &tx )
{
	string buf;
	tx = "";
	bool ac_mode = false;
	unsigned aind = 0, eln = (unsigned)end.length();
    do
    {
		if ( ac_mode )
		{
            if ( buffer[ pos ] == end[ aind ] )
			{
		        buf += buffer[ pos ];
		        aind++;
		        if ( aind == eln ) return;
			}
			else
			{
				tx 		+= buf;
                aind 	= 0;
                ac_mode = false;
                buf		= "";
			}
		}
		else
		{
			if ( buffer[ pos ] == end[ 0 ] )
			{
		        ac_mode 	= true;
		        buf 		+= buffer[ pos ];
		        aind 		= 1;
			}
			else
			{
                tx += buffer[ pos ];
			}
		}
	   pos++;
       if ( end_of_buffer() ) load_buffer();
    } while( true );
}
