// Class automatically generated by Dev-C++ New Class wizard

#ifndef BOXPLOTPLOT_H
#define BOXPLOTPLOT_H

#include "PaintFrame.h" // inheriting class's header file

/**
 * No description
 */
 
class CBoxPlot : public CPaintFrame
{
	public:
        class CSetup
		{
			public:
				CSetup();
				int type;

				double bx, by; // margins at left and down of plot
				double ex, ey; // margins at rignt and top of plot
				double ny;     // distances between text  description and axial values
				double bny;     // distance between border of plot area and description of higest bar;
				double bc;     // bar width / bars distance  coefficient. 1 - no distance betwen bars, 0 - bars haven't width an are painted by single line only
				double desc_font_height, box_values_font_height; // description font and values font sizes

				DPen 	default_pen;
				DBrush  default_brush;
		};
		
		class CBoxData
		{
			public:
				double min, q25, q50, mv, q75, max;
				const vector<double> *samples;
				string box_descriptions;
				CBoxData( double a, double b, double c, double d, double e, double f,  const vector<double> &sm, const string &ds):min( a ), q25( b ), q50( c ), mv( d ), q75( e ), max( f ), samples( &sm ),  box_descriptions( ds ) {   }
		};

        virtual void CalculateContentSize (double &x, double &y, double &fw, double &fh )  { x = 0; y = 0; fw = 100; fh = 100 * aspect; }
		void Paint( CGraphDevice &gDV ) const;
		void SetPlotDescription( const string &ds ) { plot_description = ds; }
		void AddBox( double min, double q25, double q50, double mv, double q75, double max, const vector<double> &samples, const string& ds ) { box_values.push_back( CBoxData( min, q25, q50, mv, q75, max, samples, ds ) ); }
		CSetup& GetSetup() { return setup; }
		// class constructor
		CBoxPlot( double x, double y, double w, double h, double a );
		// class destructor
		~CBoxPlot() { }
protected:
   		CBoxPlot()  { }
   		CSetup setup;

		string plot_description;
   		vector<CBoxData> box_values;
   		
   		double aspect;
};

#endif // BOXPLOTPLOT_H
