// Class automatically generated by Dev-C++ New Class wizard

#ifndef DBRUSH_H
#define DBRUSH_H

#include "color.h"

/**
 * No description
 */
class DBrush
{

public:

    DBrush():style(-1) {  }
	DBrush( const DColor &c, int s):col( c ), style( s ) { }
	DBrush( const DBrush &p ):col( p.col ), style( p.style ) { }
	const DBrush& operator=( const DBrush &p ) { col = p.col; style = p.style; return p; }
	const DColor& GetColor() const { return col; }
	int GetStyle( ) const { return style; }
    bool operator < (const DBrush &brush ) const { return col < brush.GetColor(); }

protected:
	DColor col;
	int style;
};

#endif // DBRUSH_H
