// Class automatically generated by Dev-C++ New Class wizard

#include "GraphDebugClass.h" // class's header file


// class constructor

GraphDebugClass GDBC;

// class destructor

void GraphDebugClass::CreateEPSFile( const string &filename )
{
    /*
    GraphDevicePS eps( filename.c_str() );
    eps.MakeContext();
    plot.FitToGraphDevice( eps );
    plot.Paint( eps );
    eps.DeleteContext( );
    */
}
