// Class automatically generated by Dev-C++ New Class wizard

#ifndef GRAPHDEBUGCLASS_H
#define GRAPHDEBUGCLASS_H

#include "GraphDevicePS.h"
#include "PlotXY.h"
#include <vector>
#include <string>
using namespace std;

/**
 * No description
 */
 
 
class GraphDebugClass
{
	public:
		// class constructor
	GraphDebugClass():plot( 0, 0, 200, 100, 0.67 ) { AddLine(); }
	void AddLine() { plot.AddPlotLine( CPlotLine( ) ); }
	CPlotLine::CSetup& GetLineSetup( unsigned k ) { plot.GetLine( k ).GetSetup(); }
	CPlotLine& GetLine( unsigned k ) { return plot.GetLine(k); }
	void CreateEPSFile( const string &filename );
		// class destructor
	~GraphDebugClass() { }
protected:
	CPlotXY plot;
};


extern GraphDebugClass GDBC;

#endif // GRAPHDEBUGCLASS_H
