// Class automatically generated by Dev-C++ New Class wizard

#ifndef XML_GRAPHRECEIVER_H
#define XML_GRAPHRECEIVER_H
#include "GraphDevice.h"
#include <string>
using namespace std;

/**
 * No description
 */
class xml_GraphReceiver
{
	public:


	void  OpenNode( const string &elem );
	void  AddParameter( const string &name, const string &value );
	void  AddCDATA( const string &value );
	void  AddRemark( const string &rem );
	void  AddHeader( const string &hdata );
	void  AddText( const string &tx );
	void  AddPreprocessing( const string &name, const string &cn );
	void  AddDOCTYPE( const string &nm, bool p, const string &i );
	void  CloseNode( const string &nm );

		// class constructor
		xml_GraphReceiver(CGraphDevice *g);
		// class destructor
		~xml_GraphReceiver();
		
protected:
	bool initialized, pen_array_mode, brush_array_mode, point_mode;
	double x,y,x1,y1,x2,y2,ax,ay,height,width,thickness;
	unsigned int brush_index, pen_index, color_index, R, G, B;
	int style;
	DColor col;
	DBrush brush;
	DPen   pen;
	DPoint2D point;
	vector<DPoint2D>  points;
	vector<DBrush> 	brush_array;
	vector<DPen>    pen_array;
	string current_node, text, face;
	CGraphDevice *gDC;
};

#endif // XML_GRAPHRECEIVER_H
