// Class automatically generated by Dev-C++ New Class wizard

#ifndef CHISTOGRAM_H
#define CHISTOGRAM_H

#include <vector>
#include <algorithm>
#include <string>

using namespace std;

/**
 * No description
 */
class CHistogram
{
	public:
		// class constructor
		CHistogram( ) { }
		CHistogram( const string &filename );
		CHistogram( const vector< double > &x ):values( x ) { }
		CHistogram( const CHistogram &h ):values( h.values ) { }
		const CHistogram& operator=( const CHistogram &h ) { values = h.values; return h; }
		void AddValue( double v ) { values.push_back( v ); }
		void SetData( const vector<double> &x ) { values = x ; }
		void GetMinMax( double &min, double &max ) const;
		void GetCounts( vector<double> &x, vector<unsigned int> &counts, unsigned res ) const;
		void GetCountsDouble( vector<double> &x, vector<double> &counts, unsigned res ) const;
		void GetCountsDoubleTrend( vector<double> &x, vector<double> &trend, unsigned res, unsigned np ) const;
		void Reset() { values.clear( ); }
		~CHistogram() { }
protected:
	vector<double> values;
};

inline void CHistogram::GetMinMax( double &min, double &max ) const
{
     max = *max_element( values.begin(), values.end() );
	min = *min_element( values.begin(), values.end() );
}

#endif // CHISTOGRAM_H
