// Class automatically generated by Dev-C++ New Class wizard

#ifndef HISTOGRAMPLOT_H
#define HISTOGRAMPLOT_H

#include "PaintFrame.h" // inheriting class's header file
#include "Histogram.h"

/**
 * No description
 */
class CHistogramPlot : public CPaintFrame
{
	public:
        class CSetup
		{
			public:
				CSetup();
				int type;
				unsigned int bdiv, vdiv; // respectivelly - number of bars and interval of description values at horizontal axis
				double bx, by; // margins at left and down of plot
				double ex, ey;  // margins at rignt and top of plot
				double nx, ny;  // distances between text  description and axial values
				double amx, amy;  // distance between axial values and axies
				double desc_font_height, value_font_height; // description font and values font sizes
				string vx_frm, vy_frm;  // axial values format;
				DPen 	pen;
				DBrush  brush;
		};
		
        virtual void CalculateContentSize (double &x, double &y, double &fw, double &fh )  { x = 0; y = 0; fw = 100; fh = 100 * aspect; }
		void Paint( CGraphDevice &gDV ) const;
		void SetHistogram( const CHistogram &h ) { histogram = h; }
		void SetDescription( const string &ds ) { description = ds; }
		CSetup& GetSetup() { return setup; }
		// class constructor
		CHistogramPlot( double x, double y, double w, double h, double a );
		// class destructor
		~CHistogramPlot() { }

protected:

   		CHistogramPlot( );
   		CSetup setup;
   		string description;
   		double aspect, xp, yp;
   		CHistogram histogram;

};

#endif // HISTOGRAMPLOT_H
