// Class automatically generated by Dev-C++ New Class wizard

#include "PlotLine.h" // class's header file

CPlotLine::CSetup::CSetup():line_pen( DPen( DColor(0,0,0),0,1.0 ) ),point_pen( DPen( DColor(0,0,0),0,1.0 ) ),
						point_freq( 5 ),  has_line( true ), point_type( PT_CIRC )//PT_NOTHING )
{

}


CPlotLine::CPlotLine()
{ 
    
}

CPlotLine::CPlotLine( const CPlotLine &pl )
{
	 setup = pl.setup;
	 description << pl.description.str();  
     X = pl.X;
     Y = pl.Y;
}

const CPlotLine& CPlotLine::operator=( const CPlotLine &pl )
{
	setup = pl.setup;
	description << pl.description.str();  
	X = pl.X;
	Y = pl.Y;
	return pl;
}

void CPlotLine::SetXRange( double min, double max )
{
    unsigned k,ne=(unsigned)Y.size();
    double dx = ( max - min ) / (double) ( ne - 1 );
    X.clear( );
    for(k=0; k<ne; k++) X.push_back( min + k * dx );
}

void  CPlotLine::UpdateMax( CMaxMin &mm ) const
{
    vector<double>::const_iterator i;
    for (i=X.begin(); i!=X.end(); ++i) mm.Update( 0, *i );
    for (i=Y.begin(); i!=Y.end(); ++i) mm.Update( 1, *i );

}

// class constructor

