// Class automatically generated by Dev-C++ New Class wizard

#ifndef DRECT_H
#define DRECT_H

/**
 * No description
 */
class DRect
{
        double x, y, l, h;
	public :
		DRect( double a, double b, double c, double d ) { x = a; y = b; l = c, h = d; }
		DRect( const DRect &rc ):x(rc.x),y(rc.y),l(rc.l),h(rc.h) {  }
		DRect& operator=( const DRect &rc ) { x = rc.x; y = rc.y; l = rc.l; h = rc.h; return *this; }
		bool IsNullSize() { return ( ( l == 0 ) && ( h == 0 ) ); }

        double GetX() const { return x; }
        double GetY() const { return y; }
        double GetL() const { return l; }
        double GetH() const { return h; }

protected:
   		DRect() { x = 0; y = 0; l = 0, h = 0; }

};

#endif // DRECT_H
