// Class automatically generated by Dev-C++ New Class wizard

#ifndef CMAXMIN_H
#define CMAXMIN_H

#include <vector>
#include <valarray>
#include "matrix.h" 
using namespace std;
/*
 * No description
 */
class CMaxMin
{
	public:
		// class constructor
		CMaxMin( unsigned n ):min(n),max(n) {  Reset(); }
		void Reset( );
		// class destructor
		~CMaxMin();
		
		void Update( const valarray<double> &v );
		void Update( const vector<double> &v );
		void Update( const mvector &v );
	    void Update( unsigned k, double value );
   	    double GetMin( unsigned k )  const { return min[ k ]; }
	    double GetMax( unsigned k )  const { return max[ k ]; }
	    void SetMin( unsigned k, double val )  { min[ k ] = val; }
	    void SetMax( unsigned k, double val )  { max[ k ] = val; }
  	    double GetDiff( unsigned k ) const { return max[ k ] - min[ k ]; }
  	    
    protected:
        valarray<double> min, max;
		CMaxMin();        
};

inline void CMaxMin::Update( unsigned k, double value )
{
    if ( value < min[ k ] ) min[ k ] = value;
    if ( value > max[ k ] ) max[ k ] = value;
}

#endif // CMAXMIN_H
