      subroutine vegard(igrp,nch,a0inv,eps_x,seth)

c     Vegard coeffiecients and chemical tensors
c     Input:  igrp - point group number
c               a0 - the standard crystallographic matrix A0 for nch = 0
c              nch - number of chemical components
c     Output: eps_x(6,nch) - Vegard coefficients for chemical strain
c     written by Paweł Dłużewski (since April,2005)        

      implicit none
      integer i,j,k,rot,nch,igrp
      real*8 eps_x(6,nch),eps(6,0:6,0:6),a(3,3),a0inv(3,3),fch(3,3),seth

      do k = 1,nch
         call read_a(igrp,a)
         fch = matmul(a,a0inv) ! Fch generated by k-th chemical component
         call strain3d(fch,eps,seth)
         do i = 1,6
            eps_x(i,k) = eps(i,0,0)  ! Vegard coefficients eps_x 
         enddo
      enddo
      end
